title: Alexa Felices # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist graduating with a Master's in Data Science from the University of Colorado Boulder in September 2026. 
  <br><br>
  Current IT Project Manager at Applied Materials with 10 years of data analytics and data visualization experience.
  <br><br>
  <a href="https://www.linkedin.com/in/alexa-felices-55012a91/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
